### ISSUE TITLE
'Cannot read property 'length' of undefined'

### ISSUE THREAD

**Issue by AndyBarnett** [AdamNowotny/BuildReactor#36]
One of my TeamCity projects shows everything on the extension, while another project has several jobs which show "Offline (Cannot read property 'length' of undefined)" and are grey, while 2 of the jobs in the same project are showing up.

To help me debug the reason, I need to know in which cases this error shows up. I can't tell what's different about the bad jobs vs. the good jobs. What are the variables that can cause this error?

<img width="1269" alt="screen shot 2015-09-18 at 16 10 33" src="https://cloud.githubusercontent.com/assets/1948958/9962853/e1d5c1f4-5e1f-11e5-8dc7-7a94f8fb4b01.png">

In this example, 'Build & Unit Test' at the top is a job in the same project as the grey job named 'COGAND_PublishHockeyRelease', and both jobs have finished runs in them.

**Comment by AdamNowotny** [comment]
There should be a bit more information in the background page for the extension indicating the line number where the error happened. My guess is that it could be teamcityBuild.js line 28 where it tries to parse "changes" field but would need the TeamCity response to reproduce that.

**Comment by AndyBarnett** [comment]
I had a look at the developer console for the page and only saw the following js scripts running:
main.js
main-app.js
require.js
but no teamcityBuild.js

How can I capture the TeamCity response to see where it's going wrong?

**Comment by AdamNowotny** [comment]
You need to look at the background page of the extension. To access this enable developer mode checkbox in chrome extensions page and then click "background page".
The page will have src/common/main.js and src/core/main.js loaded.
You can also see all the requests and if an error happens at least the message in the console should be more descriptive then what's passed to popup or dashboard page.

**Comment by AndyBarnett** [comment]
Ah I see, thanks, I've never used developer console before in extensions!

Looking at the serviceController.activeProjects objects, the working jobs and and broken jobs looks the same, each with isBroken, isDisabled and isRunning set to false.
This is a screenshot of the output I get when I load the page; here I'm looking at a buildOffline object which is rendering grey with the undefined problem:
![console](https://cloud.githubusercontent.com/assets/1948958/10362304/b5f0a870-6da5-11e5-8f32-9bc50abe916a.png)

and here is the full string of the stacktrace:
```xml
name: "TypeError"
stack: "TypeError: Cannot read property 'length' of undefined↵ at chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/core/main.js:1839:31↵ at chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:13519:31↵ at AnonymousObserver._onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:13447:39)↵ at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11488:12)↵ at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11417:22)↵ at AutoDetachObserverPrototype.next (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:13887:31)↵ at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11417:22)↵ at AnonymousObserver._onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:12528:22)↵ at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11488:12)↵ at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11417:22)"
url: undefined
```

I don't understand your code, is there any reason you can think of for why it can't read this build job?

**Comment by AdamNowotny** [comment]
I suspect there was a problem with parsing the last commit messages. Just published new version 0.11.0 that should fix that.

**Comment by sjkummer** [comment]
I still got this issue using BuildReactor 0.11.1 and the latest TeamCity 9.1.3 (build 37176).

**Comment by AdamNowotny** [comment]
The problem is definitely the ```httpAuth/app``` being in the url twice.
No idea how that would happen other than the url having it already.
Here is the code responsible for this request:
```
	var buildListRequest = function (self) {
		var urlPath = self.settings.username ? 'httpAuth' : 'guestAuth';
		urlPath += '/app/rest/builds?locator=buildType:' + self.id + ',running:any';
		urlPath += self.settings.branch ? ',branch:(' + self.settings.branch + ')' : '';
		return sendRequest(self, urlPath);
	};
```
Does the current version show all the builds correctly on the settings page?

**Comment by sjkummer** [comment]
I built BuildReactor from HEAD on Mac OS X and it worked. BUT: 
- as soon as I change the branch config from empty to "refs/heads/*" the "property 'length' of undefined" problem is back

**Comment by sjkummer** [comment]
Sorry, I missed your question

>> Does the current version show all the builds correctly on the settings page?
The settings page always worked in my case. Only the dashboard is broken.

**Comment by AdamNowotny** [comment]
Looks like TeamCity does not support the branch refs/heads/* and returns no builds for it. Example request:
```
https://teamcity.jetbrains.com/app/rest/builds?locator=buildType:NUnit_NUnit3_BuildAndTest,running:any,branch:(refs/heads/master)
```
which works fine for refs/heads/master, but not refs/heads/*.
There is some more information on the branch locators at https://confluence.jetbrains.com/display/TCD9/REST+API#RESTAPI-BuildLocator
 
Pushed a fix so in next version the error message should read "No build for branch [refs/heads/*]".
